name: "Continous Integration"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  precommit:
    name: Pre-Commit
    runs-on:
      - nix
      - ARM64
    steps:
      - name: Gotrade CI Environment
        uses: kirinnee/atomici-action@v2.3.1

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Run Pre-commit checks
        run: nix develop .#ci --command scripts/ci/pre-commit.sh
